# Generated by Django 5.2 on 2025-05-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coordinates',
            new_name='point',
        ),
    ]
